# Generated by Django 5.2.1 on 2025-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='tags',
            field=models.ManyToManyField(to='terms.tag'),
        ),
    ]
